#!/usr/bin/env ansible-playbook

---
- name: play 'playbook.yml'
  hosts: all
  become: yes

  vars_files:
    - defaults/main.yml

  roles:
    - { role: ant31.ruby-build,
        tags: ruby,
        ruby_version: 2.4.1
      }
    - { role: rvm_io.ruby,
        tags: rvm,
        rvm1_rubies: ['ruby-2.4.1'],
        rvm1_user: 'vagrant'
      }
    - { role: geerlingguy.mysql,
        tags: mysql
      }
    - { role: stone-payments.redis,
        tags: redis
      }

# vim:ft=ansible:
