#!/usr/bin/env ansible-playbook

---
- name: play 'playbook.yml'
  hosts: all
  become: yes

  vars_files:
    - defaults/main.yml

  roles:
    - { role: mediapeers.ruby,
        tags: ruby,
        ruby_version_string: 2.2.3
      }
    - { role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3.1'],
        rvm1_user: 'vagrant'
      }
    - { role: geerlingguy.mysql,
        tags: mysql
      }
    - { role: stone-payments.redis,
        tags: redis
      }

# vim:ft=ansible:
